#!/bin/bash
sudo firewall-cmd --permanent --add-port=5601/tcp
sudo firewall-cmd --reload
wget https://artifacts.elastic.co/downloads/kibana/kibana-7.15.2-x86_64.rpm
sha512sum -c kibana-7.15.2-x86_64.rpm 
sudo rpm -ivh kibana-7.15.2-x86_64.rpm
sudo systemctl daemon-reload
sudo systemctl enable --now kibana.service
sudo systemctl restart firewalld
sudo echo 'server.host: "0.0.0.0"' >> /etc/kibana/kibana.yml
sudo systemctl restart kibana.service
sudo systemctl status kibana.service
